language: groovy
rvm:
- 1.8.8
install:
- gradle build
before_script:
- gradle test
- export PLUGIN_VERSION=${TRAVIS_COMMIT:0:7}
script:
- gradle -PpluginVersion=${PLUGIN_VERSION}
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: b3u+T0iqaZQWNggEIWHs2eM1PMxCcbfNvHh2MCCIpIrJo4p7euXEzFUvyRFgBvYLtLFY74Isd2DmeH0RI+6tXuj0pajj9PX04KPTsrzANX4ovXsXoO8g96l27RFhBmEUiEafTa7SAGyaRPwWo1I4DTISZ8MgpDkPREAdjo4kKclmFQbX+Ouy8ih788K/EOHapNTaTzEBVdO8XiFK+77Ek4Su6HAxfUy+9/0R2rF3eAUxsNitEfI7oj2V0N+dsEBTVy8GXgiJfLIG9szjUZ6lhUisOlt6C70NAaCtqbpTrAeFfRykKEMGqyuzt4axKk+1IE90l6+FuDWA7SdT4D1Ikx+PcfkF8JguJ6OpIzM6h50J0Veaq2H6fAJ5ZGA1i1DbYsKDNRPHS/3IUwN2hiz2LE/2QBh5qEaoLZHMQ3ORUdwI81OzsN7xjtr6jv9BvXBymuxizBU81JUKHg55mMHg1Sgv8om+W4r9o2gFLQ+CGnMnshTEQ601eqPQWJ84oZRmBEn86CdUlJd+NW95ksRJaB54CqCIKD1dJLKndT3QLXSrk7HnMfUhQXltg17Q2GlisjAGbh7zQuC7Z5bkqyeeBh4jz7wuJqKOJwnBi6QSsNU0nqUqR6lJXYOybURr8yshksDuZ11Eff1USExe838zPlG0/KGNTxj0HWaZeYTgqPY=
    on_success: change
    on_failure: change
  email: false
deploy:
  provider: releases
  api_key:
    secure: $GITAUTH
  file_glob: true
  file: build/distributions/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: DasJayYa/Jenkins-Job-Manager-UCD
