language: groovy
rvm:
- 1.8.8
install:
- gradle build
before_script:
- gradle test
- export PLUGIN_VERSION=${TRAVIS_COMMIT:0:7}
script:
- gradle -PpluginVersion=${PLUGIN_VERSION}
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: $GITAUTH
  file_glob: true
  file: build/distributions/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: DasJayYa/Jenkins-Job-Manager-UCD
